name          'opentable/teamcity'
version       '1.0.0'
source        'git://github.com/opentable/puppet-teamcity.git'
author        'opentable'
summary       'Module for managing TeamCity agents and servers'
description   'Install and manage the installation of agents and servers for TeamCity'
project_page  'https://github.com/opentable/puppet-teamcity'
license       'MIT'
dependency    'puppetlabs/stdlib', '>= 3.2.0'
